/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './browser';
import * as i1 from './transfer-state';
import * as i2 from '@angular/core';
export function BrowserTransferStateModuleNgSummary():any[] {
  return [{summaryKind:2,type:{reference:i0.BrowserTransferStateModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},entryComponents:([] as any[]),providers:[{provider:{token:{identifier:{reference:i1.TransferState}},
      useClass:(null as any),useValue:(undefined as any),useFactory:{reference:i0.getTransferState,
          diDeps:([] as any[])},useExisting:(undefined as any),deps:([] as any[]),
      multi:false},module:{reference:i0.BrowserTransferStateModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i2.APP_INITIALIZER}},
      useClass:(null as any),useValue:(undefined as any),useFactory:{reference:i0.getTransferInitializer,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i1.TransferState}}}]},useExisting:(undefined as any),
      deps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i1.TransferState}}}],multi:true},module:{reference:i0.BrowserTransferStateModule,
      diDeps:([] as any[]),lifecycleHooks:([] as any[])}}],modules:[{reference:i0.BrowserTransferStateModule,
      diDeps:([] as any[]),lifecycleHooks:([] as any[])}],exportedDirectives:([] as any[]),
      exportedPipes:([] as any[])}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2hlZWt0ZWFtMDEvRG9jdW1lbnRzL1dvcmtzcGFjZXMvYW5ndWxhci11bml2ZXJzYWwtdHJhbnNmZXItc3RhdGUvc3JjL2Jyb3dzZXIubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvaGVla3RlYW0wMS9Eb2N1bWVudHMvV29ya3NwYWNlcy9hbmd1bGFyLXVuaXZlcnNhbC10cmFuc2Zlci1zdGF0ZS9zcmMvYnJvd3Nlci50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
