/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './server';
import * as i1 from './transfer-state';
import * as i2 from '@angular/platform-server';
import * as i3 from '@angular/core';
export function ServerTransferStateModuleNgSummary():any[] {
  return [{summaryKind:2,type:{reference:i0.ServerTransferStateModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},entryComponents:([] as any[]),providers:[{provider:{token:{identifier:{reference:i1.TransferState}},
      useClass:{reference:i0.ServerTransferState,diDeps:[{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.PlatformState}}},
          {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i3.RendererFactory2}}}],lifecycleHooks:([] as any[])},
      useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
      deps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.PlatformState}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.RendererFactory2}}}],
      multi:false},module:{reference:i0.ServerTransferStateModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])}}],modules:[{reference:i0.ServerTransferStateModule,
      diDeps:([] as any[]),lifecycleHooks:([] as any[])}],exportedDirectives:([] as any[]),
      exportedPipes:([] as any[])},{summaryKind:3,type:{reference:i0.ServerTransferState,
      diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.PlatformState}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.RendererFactory2}}}],
      lifecycleHooks:([] as any[])}}];
}
export function ServerTransferStateNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.ServerTransferState,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.PlatformState}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i3.RendererFactory2}}}],lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2hlZWt0ZWFtMDEvRG9jdW1lbnRzL1dvcmtzcGFjZXMvYW5ndWxhci11bml2ZXJzYWwtdHJhbnNmZXItc3RhdGUvc3JjL3NlcnZlci5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9oZWVrdGVhbTAxL0RvY3VtZW50cy9Xb3Jrc3BhY2VzL2FuZ3VsYXItdW5pdmVyc2FsLXRyYW5zZmVyLXN0YXRlL3NyYy9zZXJ2ZXIudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
