/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './transfer-state';
import * as i1 from '@angular/http';
export function TransferHttpModuleNgSummary():any[] {
  return [{summaryKind:2,type:{reference:i0.TransferHttpModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},entryComponents:([] as any[]),providers:[{provider:{token:{identifier:{reference:i0.TransferHttp,
      diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i1.Http}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i0.TransferState}}}],
      lifecycleHooks:([] as any[])}},useClass:{reference:i0.TransferHttp,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Http}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i0.TransferState}}}],lifecycleHooks:([] as any[])},
      useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
      deps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i1.Http}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i0.TransferState}}}],
      multi:false},module:{reference:i0.TransferHttpModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}}],
      modules:[{reference:i0.TransferHttpModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}],
      exportedDirectives:([] as any[]),exportedPipes:([] as any[])},{summaryKind:3,
      type:{reference:i0.TransferHttp,diDeps:[{isAttribute:false,isHost:false,isSelf:false,
          isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Http}}},
          {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i0.TransferState}}}],lifecycleHooks:([] as any[])}}];
}
export function TransferStateNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.TransferState,diDeps:([] as any[]),lifecycleHooks:([] as any[])}}];
}
export function TransferHttpNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.TransferHttp,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Http}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i0.TransferState}}}],lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2hlZWt0ZWFtMDEvRG9jdW1lbnRzL1dvcmtzcGFjZXMvYW5ndWxhci11bml2ZXJzYWwtdHJhbnNmZXItc3RhdGUvc3JjL3RyYW5zZmVyLXN0YXRlLm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2hlZWt0ZWFtMDEvRG9jdW1lbnRzL1dvcmtzcGFjZXMvYW5ndWxhci11bml2ZXJzYWwtdHJhbnNmZXItc3RhdGUvc3JjL3RyYW5zZmVyLXN0YXRlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
